version: '3.7'

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: base
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    network_mode:
      host